name: "ethics_virtue"
source: "hendrycks/ethics"
subset: "virtue"
keep_columns: ["scenario", "label"]

mappings:
  task_type: "binary"
  prompt: "scenario"
  split: "train"
  target:
    input: "selections"
    value: "options"