dataset:
  name: "conversation_dataset"
  version: "1.0.0"
  description: "Conversation dataset with performance metrics and attributes"

ingestion:
  source_path: "datasets/conversation_dataset/raw"
  file_pattern: "*.parquet"
  encoding: "utf-8"

preprocessing:
  columns:
    - name: "text"
      source: "opening_prompt"
      type: "string"
      required: true
    - name: "conversation_history"
      source: "conversation_history"
      type: "array"
      required: true
    - name: "metadata"
      type: "object"
      required: true
      fields:
        - name: "conversation_id"
          source: "conversation_id"
          type: "string"
        - name: "user_id"
          source: "user_id"
          type: "string"
        - name: "conversation_type"
          source: "conversation_type"
          type: "string"
        - name: "conversation_turns"
          source: "conversation_turns"
          type: "integer"
        - name: "performance_metrics"
          source: "performance_attributes"
          type: "object"
        - name: "choice_metrics"
          source: "choice_attributes"
          type: "object"
        - name: "feedback"
          source: "open_feedback"
          type: "string"
        - name: "timing"
          type: "object"
          fields:
            - name: "duration_seconds"
              source: "timing_duration_s"
              type: "float"
            - name: "duration_minutes"
              source: "timing_duration_mins"
              type: "float"
        - name: "generated_at"
          source: "generated_datetime"
          type: "timestamp"
        - name: "in_balanced_subset"
          source: "included_in_balanced_subset"
          type: "boolean"

transformation:
  text_processing:
    remove_punctuation: true
    remove_numbers: false
    min_length: 10
  conversation_processing:
    max_turns: 222
    include_history: true
    include_metadata: true

output:
  path: "datasets/conversation_dataset/processed"
  format: "parquet"
  compression: "snappy"
  partition_by: ["conversation_type"] 