name: "lamp_news_headline"
source: "LaMP_4"
task_type: "generation"
data_files:
  train:
    questions: "train/train_questions.json"
    outputs: "train/train_outputs.json"
base_url: "https://ciir.cs.umass.edu/downloads/LaMP/LaMP_4"

mappings:
  task_type: "generation"
  prompt: "input"
  output: "output"
  split: "train"
  annotation:
    type: "generation"
    value: "output"
    choices: []
  user_profile:
    characteristics: {}
    stated_preferences:
      pairwise: []
      scored: []
      categorical: []
      ranked_lists: []
      freeform_text: []
    observed_preferences:
      click_data: []
      chosen_options: []
    behavior:
      input_field: "profile.text"
      output_field: "profile.title" 