name: "longlamp_product"
source: "LongLaMP/LongLaMP"
subset: "product_review_user"
task_type: "generation"

mappings:
  task_type: "generation"
  prompt: "input"
  output: "output"
  split: "train"
  annotation:
    type: "generation"
    value: "output"
    choices: []
  user_profile:
    characteristics: {}
    stated_preferences:
      pairwise: []
      scored: []
      categorical: []
      ranked_lists: []
      freeform_text: []
    observed_preferences:
      click_data: []
      chosen_options: []
    behavior:
      template: "Generate the review text written by a reviewer who has a given overall rating of '{profile.overall}' for a product with description \"{profile.description}\". The summary of the review text is \"{profile.summary}\"."
      output_field: "profile.reviewText" 