name: "longlamp_abstract"
source: "LongLaMP/LongLaMP"
subset: "abstract_generation_user"
task_type: "generation"

mappings:
  task_type: "generation"
  prompt: "input"
  output: "output"
  split: "train"
  annotation:
    type: "generation"
    value: "output"
    choices: []
  user_profile:
    characteristics: {}
    stated_preferences:
      pairwise: []
      scored: []
      categorical: []
      ranked_lists: []
      freeform_text: []
    observed_preferences:
      click_data: []
      chosen_options: []
    behavior:
      - input: "profile.title"
        output: "profile.abstract" 