name: "opinionqa"
type: "merge"
merge_key: "user_id"
merge_sources:
  - name: "survey"
    source: "HannahRoseKirk/prism-alignment"
    subset: "survey"
    keep_columns: ["user_id", "employment_status", "education"]
  - name: "utterances"
    source: "HannahRoseKirk/prism-alignment"
    subset: "utterances"
    keep_columns: ["user_id", "model_response", "score", "user_prompt"]

mappings:
  task_type: "ranking"
  prompt: "utterances.user_prompt"
  output: "utterances.model_response"
  split: "train"
  annotation:
    type: "ranking"
    value: "utterances.score"
  user_profile:
    characteristics:
      - "survey.employment_status"
      - "survey.education"
    stated_preferences:
      pairwise: []
      scored: []
      categorical: []
      ranked_lists: []
      freeform_text:
        - "survey.response"
        - "utterances.user_prompt"
    observed_preferences:
        pairwise: []
        scored: []
        categorical: []
        ranked_lists: []
        freeform_text: []
    behavior: "merge_metadata(user_id)"




