name: "prism_merged"
type: "merge"
merge_key: "user_id"
merge_sources:
  - name: "survey"
    source: "HannahRoseKirk/prism-alignment"
    subset: "survey"
    keep_columns: ["user_id", "response", "alignment"]
  - name: "utterances"
    source: "HannahRoseKirk/prism-alignment"
    subset: "utterances"
    keep_columns: ["user_id", "utterance", "stance"]

mappings:
  task_type: "classification"
  prompt: "merge(survey.response, utterances.utterance)"
  split: "train"
  annotation:
    type: "classification"
    value: "utterances.stance"
  user_profile:
    preferences:
      freeform_text: "survey.response"
    interaction_history: "merge_metadata(user_id)"
